from typing import Annotated, Sequence, List, Dict, Any, Literal
from datetime import date, timedelta, datetime
from typing_extensions import TypedDict, Optional
from langchain_openai import ChatOpenAI
from langchain_core.messages import BaseMessage
from tradereact.agents import *
from langgraph.prebuilt import ToolNode
from langgraph.graph import END, StateGraph, START
from langgraph.graph.message import add_messages, MessagesState


# Researcher team state
class InvestDebateState(TypedDict):
    bull_history: Annotated[
        str, "Bullish Conversation history"
    ]  # Bullish Conversation history, Bull Researcher的所有发言历史
    bear_history: Annotated[
        str, "Bearish Conversation history"
    ]  # Bullish Conversation history, Bear Researcher的所有发言历史
    history: Annotated[str, "Conversation history"]  # Conversation history, 完整的对话历史(交替记录)
    current_response: Annotated[str, "Latest response"]  # Last response, 最新一轮的发言内容
    judge_decision: Annotated[str, "Final judge decision"]  # Last response, Research Manager的裁决结果
    count: Annotated[int, "Length of the current conversation"]  # Conversation length, 对话轮数计数器


# Risk management team state
class RiskDebateState(TypedDict):
    risky_history: Annotated[
        str, "Risky Agent's Conversation history"
    ]  # Conversation history, Risky Analyst的所有发言
    safe_history: Annotated[
        str, "Safe Agent's Conversation history"
    ]  # Conversation history, Safe Analyst的所有发言
    neutral_history: Annotated[
        str, "Neutral Agent's Conversation history"
    ]  # Conversation history, Neutral Analyst的所有发言
    history: Annotated[str, "Conversation history"]  # Conversation history, 完整的三方对话历史
    latest_speaker: Annotated[str, "Analyst that spoke last"]   # 最新发言者 ("Risky" | "Safe" | "Neutral")
    current_risky_response: Annotated[
        str, "Latest response by the risky analyst"
    ]  # Last response
    current_safe_response: Annotated[
        str, "Latest response by the safe analyst"
    ]  # Last response
    current_neutral_response: Annotated[
        str, "Latest response by the neutral analyst"
    ]  # Last response
    judge_decision: Annotated[str, "Judge's decision"]  #Risk Judge的最终裁决
    count: Annotated[int, "Length of the current conversation"]  # Conversation length, 发言计数器


class AgentState(MessagesState):
    # ========== 基础信息 ==========
    company_of_interest: Annotated[str, "Company that we are interested in trading"]
    trade_date: Annotated[str, "What date we are trading at"]

    sender: Annotated[str, "Agent that sent this message"]

    # research step
    market_report: Annotated[str, "Report from the Market Analyst"]
    sentiment_report: Annotated[str, "Report from the Social Media Analyst"]
    news_report: Annotated[str, "Report from the News Researcher of current world affairs"]
    fundamentals_report: Annotated[str, "Report from the Fundamentals Researcher"]

    # researcher team discussion step
    investment_debate_state: Annotated[
        InvestDebateState, "Current state of the debate on if to invest or not"
    ]
    investment_plan: Annotated[str, "Plan generated by the Analyst"]

    trader_investment_plan: Annotated[str, "Plan generated by the Trader"]

    # risk management team discussion step
    risk_debate_state: Annotated[
        RiskDebateState, "Current state of the debate on evaluating risk"
    ]
    final_trade_decision: Annotated[str, "Final decision made by the Risk Analysts"]
